In [22]:
import numpy as np

In [23]:
AA = np.arange(12*10).reshape(12,10)
print(AA)

iicxn = AA.shape[1]
iicyn = AA.shape[0]
print(iicxn)
print(iicyn)

[[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]]
10
12


In [31]:
# idx = 116
# cnt_x = 5
# cnt_y = 11

cnt_x = 0
cnt_y = 0
cnt = 0

x_periodic = True

for idx in range(iicxn * iicyn):
    
    topleft = idx - iicxn - 1
    midleft = idx - 1
    botleft = idx + iicxn - 1

    topmid = idx - iicxn
    midmid = idx
    botmid = idx + iicxn

    topright = idx - iicxn + 1
    midright = idx + 1
    botright = idx + iicxn + 1

    if cnt_x == 0:
        topleft += iicxn - 1
        midleft += iicxn - 1
        botleft += iicxn - 1

        if x_periodic:
            topmid += iicxn - 1
            midmid += iicxn - 1
            botmid += iicxn - 1

    if cnt_x == iicxn - 1:
        topright -= iicxn - 1
        midright -= iicxn - 1
        botright -= iicxn - 1

        if x_periodic:
            topmid -= iicxn - 1
            midmid -= iicxn - 1
            botmid -= iicxn - 1


    if cnt_y == 0:
        topleft += (iicxn * (iicyn))
        topmid += (iicxn * (iicyn))
        topright += (iicxn * (iicyn))

    if cnt_y == iicyn - 1:
        botleft -= (iicxn * (iicyn))
        botmid -= (iicxn * (iicyn))
        botright -= (iicxn * (iicyn))
        
    stencil = [[topleft, topmid, topright],[midleft, midmid, midright],[botleft,botmid,botright]]
    stencil = np.array(stencil)
    

    print(AA.ravel()[stencil.ravel()].reshape(3,3))
    print("%d -------------------------------\n" %cnt)
    cnt += 1
    cnt_x += 1
    if cnt_x % iicxn == 0:
        cnt_y += 1
        cnt_x = 0

[[118 119 111]
 [  8   9   1]
 [ 18  19  11]]
0 -------------------------------

[[110 111 112]
 [  0   1   2]
 [ 10  11  12]]
1 -------------------------------

[[111 112 113]
 [  1   2   3]
 [ 11  12  13]]
2 -------------------------------

[[112 113 114]
 [  2   3   4]
 [ 12  13  14]]
3 -------------------------------

[[113 114 115]
 [  3   4   5]
 [ 13  14  15]]
4 -------------------------------

[[114 115 116]
 [  4   5   6]
 [ 14  15  16]]
5 -------------------------------

[[115 116 117]
 [  5   6   7]
 [ 15  16  17]]
6 -------------------------------

[[116 117 118]
 [  6   7   8]
 [ 16  17  18]]
7 -------------------------------

[[117 118 119]
 [  7   8   9]
 [ 17  18  19]]
8 -------------------------------

[[118 110 111]
 [  8   0   1]
 [ 18  10  11]]
9 -------------------------------

[[ 8  9  1]
 [18 19 11]
 [28 29 21]]
10 -------------------------------

[[ 0  1  2]
 [10 11 12]
 [20 21 22]]
11 -------------------------------

[[ 1  2  3]
 [11 12 13]
 [21 22 23]]
12 ----

In [25]:
print(AA.ravel()[idx])

119


In [26]:

# print(AA.ravel()[stencil.ravel()])

In [27]:
def negative_symmetric(vector,pad_width,iaxis,kwargs=None):
    if pad_width[1] > 0:
        sign = -1.
        vector[:pad_width[0]] = sign * vector[pad_width[0]:2*pad_width[0]][::-1]
        vector[-pad_width[1]:] = sign * vector[-2*pad_width[1]:-pad_width[1]][::-1]
        return vector
    else: # axis must have length > 0 for padding
        return vector

In [28]:
print(np.pad(AA,((0,0),(2,2)),negative_symmetric))

[[  -1    0    0    1    2    3    4    5    6    7    8    9   -9   -8]
 [ -11  -10   10   11   12   13   14   15   16   17   18   19  -19  -18]
 [ -21  -20   20   21   22   23   24   25   26   27   28   29  -29  -28]
 [ -31  -30   30   31   32   33   34   35   36   37   38   39  -39  -38]
 [ -41  -40   40   41   42   43   44   45   46   47   48   49  -49  -48]
 [ -51  -50   50   51   52   53   54   55   56   57   58   59  -59  -58]
 [ -61  -60   60   61   62   63   64   65   66   67   68   69  -69  -68]
 [ -71  -70   70   71   72   73   74   75   76   77   78   79  -79  -78]
 [ -81  -80   80   81   82   83   84   85   86   87   88   89  -89  -88]
 [ -91  -90   90   91   92   93   94   95   96   97   98   99  -99  -98]
 [-101 -100  100  101  102  103  104  105  106  107  108  109 -109 -108]
 [-111 -110  110  111  112  113  114  115  116  117  118  119 -119 -118]]


In [29]:
BB = np.arange(20*11).reshape(20,11)
print(BB)

[[  0   1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20  21]
 [ 22  23  24  25  26  27  28  29  30  31  32]
 [ 33  34  35  36  37  38  39  40  41  42  43]
 [ 44  45  46  47  48  49  50  51  52  53  54]
 [ 55  56  57  58  59  60  61  62  63  64  65]
 [ 66  67  68  69  70  71  72  73  74  75  76]
 [ 77  78  79  80  81  82  83  84  85  86  87]
 [ 88  89  90  91  92  93  94  95  96  97  98]
 [ 99 100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130 131]
 [132 133 134 135 136 137 138 139 140 141 142]
 [143 144 145 146 147 148 149 150 151 152 153]
 [154 155 156 157 158 159 160 161 162 163 164]
 [165 166 167 168 169 170 171 172 173 174 175]
 [176 177 178 179 180 181 182 183 184 185 186]
 [187 188 189 190 191 192 193 194 195 196 197]
 [198 199 200 201 202 203 204 205 206 207 208]
 [209 210 211 212 213 214 215 216 217 218 219]]


In [30]:
igy = 2
SLC = (slice(None),slice(igy,igy+1))

print(BB[SLC])

[[  2]
 [ 13]
 [ 24]
 [ 35]
 [ 46]
 [ 57]
 [ 68]
 [ 79]
 [ 90]
 [101]
 [112]
 [123]
 [134]
 [145]
 [156]
 [167]
 [178]
 [189]
 [200]
 [211]]
