In [2]:
import numpy as np
from copy import deepcopy

import logging

N = 10

# class member(object):
#     A = 10
#     B = 2
#     C = 'D'

mem = np.arange(25).reshape(5,5)
logging.info(mem)
def sampler(ic):
    # ic.A += np.random.randint(5)
    ic += np.random.randint(5)

class ensemble(object):
    def __init__(self):
        None
        
    def ensemble(self):
        for key,value in vars(self).items():
            setattr(self,key,value)

    def set_members(self,ic,N,sampler):
        cnt = 0
        for _ in range(N):
            mem = deepcopy(ic)
            sampler(mem)
            setattr(self,'mem_' + str(cnt),mem)
            cnt += 1

    def get_mean(self, ensemble):
        return self.members(ensemble).sum(axis=0)

    def get_covariance(self, ensemble):
        ensemble_mean = self.get_mean(ensemble)
        N = ensemble.members(ensemble).shape[0]
        ensemble_list = ensemble.members(ensemble)
        distance = ensemble_list - ensemble_mean
        ensemble_covar = 1./(N-1.) * (distance.transpose((0,2,1)) @ distance).sum(axis=0)
        return ensemble_covar

    @staticmethod
    def members(ensemble):
        return np.array(list(ensemble.__dict__.values()))


    # def __repr__(ensemble):
    #     return ensemble.__dict__.values()

ens = ensemble()
ens.set_members(mem,N,sampler)



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [21]:
np.random.seed(555)

n = 5
A = np.random.randn(n,n)
A = 0.5 * (A + A.T)
A += n*np.eye(n)
logging.info(A)

from scipy.linalg import inv, eig, sqrtm
Ba = inv(A)
# logging.info(Ba)

Lambda, P = eig(A)
Lambda, P = Lambda.real, P.real
Bb = P @ np.diag(1./Lambda) @ P.T
# logging.info(Bb)

Ca = sqrtm(inv(A))
logging.info(Ca)
Cb = P @ np.diag(1./Lambda)**0.5 @ P.T
logging.info(Cb)

[[ 5.1482272   0.39528647 -0.24543144  0.62243707 -0.21077202]
 [ 0.39528647  4.15377852  2.10995097  1.05466316 -0.21745041]
 [-0.24543144  2.10995097  4.95997786 -0.9573476  -0.99770965]
 [ 0.62243707  1.05466316 -0.9573476   5.79831093 -1.62908966]
 [-0.21077202 -0.21745041 -0.99770965 -1.62908966  5.04546801]]
[[ 0.44454312 -0.02398683  0.01781652 -0.01718851  0.00744508]
 [-0.02398683  0.57335197 -0.16137779 -0.09070019 -0.03620126]
 [ 0.01781652 -0.16137779  0.53190154  0.09110248  0.07786727]
 [-0.01718851 -0.09070019  0.09110248  0.46268557  0.08890108]
 [ 0.00744508 -0.03620126  0.07786727  0.08890108  0.47888151]]
[[ 0.44454312 -0.02398683  0.01781652 -0.01718851  0.00744508]
 [-0.02398683  0.57335197 -0.16137779 -0.09070019 -0.03620126]
 [ 0.01781652 -0.16137779  0.53190154  0.09110248  0.07786727]
 [-0.01718851 -0.09070019  0.09110248  0.46268557  0.08890108]
 [ 0.00744508 -0.03620126  0.07786727  0.08890108  0.47888151]]
